import { jsPDF } from 'jspdf';
import 'jspdf-autotable';
import * as XLSX from 'xlsx';

export interface ExportColumn {
  header: string;
  dataKey: string;
}

export interface ExportOptions {
  format: 'pdf' | 'excel';
  title: string;
  columns: ExportColumn[];
  data: any[];
  companyName?: string;
  generatedBy?: string;
}

export const exportData = ({
  format,
  title,
  columns,
  data,
  companyName = 'Apni Estate Enterprise',
  generatedBy = 'System User'
}: ExportOptions) => {
  const dateStr = new Date().toLocaleDateString('en-IN', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  });

  if (format === 'excel') {
    // Transform data according to columns
    const excelData = data.map(item => {
      const row: any = {};
      columns.forEach(col => {
        let val = item[col.dataKey];
        // simple formatting for nested objects or arrays if needed
        if (typeof val === 'object' && val !== null) {
            val = JSON.stringify(val);
        }
        row[col.header] = val;
      });
      return row;
    });

    const worksheet = XLSX.utils.json_to_sheet(excelData);
    
    // Auto-size columns based on content
    const colWidths = columns.map(col => {
      const maxContentLength = Math.max(
        col.header.length,
        ...excelData.map(r => String(r[col.header] || '').length)
      );
      return { wch: Math.min(Math.max(maxContentLength, 10), 50) };
    });
    worksheet['!cols'] = colWidths;

    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, worksheet, 'Export Data');

    const fileName = `${title.replace(/\s+/g, '_')}_${dateStr.split(',')[0].replace(/ /g, '')}.xlsx`;
    XLSX.writeFile(workbook, fileName);
  } else if (format === 'pdf') {
    const doc = new jsPDF('landscape');
    
    // Header
    doc.setFontSize(20);
    doc.setTextColor(10, 61, 145); // Primary color
    doc.text(companyName, 14, 22);
    
    doc.setFontSize(14);
    doc.setTextColor(50, 50, 50);
    doc.text(title, 14, 32);
    
    // Metadata
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`Generated on: ${dateStr}`, 14, 40);
    doc.text(`Generated by: ${generatedBy}`, 14, 45);
    
    // Table Data
    const tableData = data.map(item => 
      columns.map(col => {
        let val = item[col.dataKey];
        if (typeof val === 'object' && val !== null) return JSON.stringify(val);
        return val !== undefined && val !== null ? String(val) : '';
      })
    );

    // @ts-ignore
    doc.autoTable({
      head: [columns.map(c => c.header)],
      body: tableData,
      startY: 55,
      theme: 'grid',
      styles: {
        fontSize: 9,
        cellPadding: 4,
      },
      headStyles: {
        fillColor: [10, 61, 145], // Primary color
        textColor: [255, 255, 255],
        fontStyle: 'bold',
      },
      alternateRowStyles: {
        fillColor: [249, 250, 251], // light gray
      },
      margin: { top: 55 },
      didDrawPage: function (data: any) {
        // Footer with page number
        const pageCount = doc.getNumberOfPages();
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text(
          `Page ${data.pageNumber} of ${pageCount} — ${companyName} ERP`,
          data.settings.margin.left,
          doc.internal.pageSize.height - 10
        );
      }
    });

    const fileName = `${title.replace(/\s+/g, '_')}_${dateStr.split(',')[0].replace(/ /g, '')}.pdf`;
    doc.save(fileName);
  }
};
