import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';

export function generateDprPdf(report: any, siteName: string) {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(20);
  doc.setTextColor(10, 61, 145); // Brand primary
  doc.text('APNI ESTATE', 14, 22);
  
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text('Daily Progress Report (DPR)', 14, 32);
  
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Site: ${siteName}`, 14, 40);
  doc.text(`Date: ${format(new Date(report.report_date), 'dd MMM yyyy')}`, 14, 46);
  doc.text(`Report ID: ${report.id.substring(0, 8).toUpperCase()}`, 14, 52);

  // Line separator
  doc.setDrawColor(200, 200, 200);
  doc.line(14, 56, 196, 56);

  let startY = 64;

  // Key Metrics Table
  autoTable(doc, {
    startY: startY,
    head: [['Weather', 'Workforce Present', 'Supervisor']],
    body: [
      [report.weather || 'Clear', `${report.workers_count || 0} Workers`, report.submitter?.name || 'Supervisor']
    ],
    theme: 'grid',
    headStyles: { fillColor: [240, 240, 240], textColor: [0, 0, 0] },
    margin: { left: 14 }
  });

  startY = (doc as any).lastAutoTable.finalY + 10;

  // Sections
  const sections = [
    { title: 'Executive Summary', content: report.summary },
    { title: 'Work Completed Today', content: report.work_completed },
    { title: 'Materials Consumed', content: report.materials_consumed },
    { title: 'Issues Faced', content: report.issues_faced },
    { title: "Tomorrow's Plan", content: report.tomorrow_plan },
  ];

  sections.forEach(section => {
    if (section.content) {
      doc.setFontSize(12);
      doc.setTextColor(10, 61, 145);
      doc.text(section.title, 14, startY);
      
      doc.setFontSize(10);
      doc.setTextColor(50, 50, 50);
      
      const lines = doc.splitTextToSize(section.content, 180);
      doc.text(lines, 14, startY + 6);
      
      startY += (lines.length * 5) + 12;

      if (startY > 270) {
        doc.addPage();
        startY = 20;
      }
    }
  });

  // Footer
  const pageCount = (doc.internal as any).getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(`Page ${i} of ${pageCount}`, 196, 285, { align: 'right' });
    doc.text('Generated by Apni Estate ERP', 14, 285);
  }

  return doc;
}

export function generateInvoicePdf(invoice: any, vendor: any) {
  const doc = new jsPDF();
  
  doc.setFontSize(24);
  doc.setTextColor(10, 61, 145);
  doc.text('INVOICE', 196, 22, { align: 'right' });
  
  doc.setFontSize(16);
  doc.text('APNI ESTATE', 14, 22);
  
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Invoice #: ${invoice.number}`, 196, 32, { align: 'right' });
  doc.text(`Date: ${format(new Date(invoice.created_at), 'dd MMM yyyy')}`, 196, 38, { align: 'right' });
  doc.text(`Due Date: ${format(new Date(invoice.due_date), 'dd MMM yyyy')}`, 196, 44, { align: 'right' });

  doc.setTextColor(50, 50, 50);
  doc.text('Bill To:', 14, 38);
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.text(vendor?.name || 'Vendor', 14, 44);
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  if (vendor?.address) doc.text(vendor.address, 14, 50);
  if (vendor?.gst_number) doc.text(`GSTIN: ${vendor.gst_number}`, 14, 56);

  autoTable(doc, {
    startY: 70,
    head: [['Description', 'Amount']],
    body: [
      [invoice.notes || 'Project Services / Materials', `Rs. ${invoice.amount.toFixed(2)}`],
      ['Tax Amount', `Rs. ${(invoice.tax_amount || 0).toFixed(2)}`]
    ],
    theme: 'striped',
    headStyles: { fillColor: [10, 61, 145] },
  });

  const finalY = (doc as any).lastAutoTable.finalY + 10;
  
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text(`Total Amount: Rs. ${invoice.total.toFixed(2)}`, 196, finalY, { align: 'right' });

  return doc;
}
